import Head from 'next/head'
import TreeOrg from '@/components/TreeOrg'


export default function Home() {
  return (
    <>
      <Head>
        <title>Tree Org Visualizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TreeOrg />
      </main>
    </>
  )
}
